### ISSUE TITLE
Replace yarn by npm

### ISSUE THREAD

**Issue by LeBenLeBen** [frctl/fractal-docs#47]
To be consistent with the other repositories of the organization and allows this one to be part of the monorepo later on.

**Comment by risker** [comment]
There's only one dependency so nothing else needs to be done, I believe. I'd rename the package to `@frctl/docs` and mark it as private in package.json but that can be done when importing to the monorepo.

**Comment by anitagraham** [comment]
Is there a problem with a user using yarn to install fractal?
If not, then it would be helpful to include the yarn commands as part of the install docs.
Particularly the difference between "Install Fractal" and "Install Fractal CLI"
