### ISSUE TITLE
Handful of broken links - Redirect rules need adding to _redirects file

### ISSUE THREAD

**Issue by samuelgoddard** [frctl/fractal-docs#5]
There are still a bunch of broken links that need redirect rules adding. The redirects file can be found in the following directory `fractal-docs/docs/.vuepress/public/`

https://fractal.build/guide/web/server/
https://fractal.build/guide/components/configuration/
https://fractal.build/guide/docs/
https://fractal.build/guide/integration/production/
https://fractal.build/api/endpoints/cli/
https://fractal.build/api/endpoints/web/
https://fractal.build/guide/cli/interactive/
https://fractal.build/guide/cli/commands/
https://fractal.build/guide/collections/configuration/
https://fractal.build/guide/web/builder/
https://fractal.build/api/endpoints/docs/
https://fractal.build/guide/web/configuration/
https://fractal.build/api/endpoints/components/
https://fractal.build/guide/docs/configuration/
https://fractal.build/guide/components/sub-components/
https://fractal.build/guide/cli/custom-commands/

**Comment by fohlin** [comment]
@samuelgoddard Seems fixed as of d9bbe8d8b76, no? (Thanks! 👍)

**Comment by samuelgoddard** [comment]
@fohlin Ah yes, I forgot to close this issue! Thanks for the reminder
