### ISSUE TITLE
Copy on Collection Configuration page is out of order

### ISSUE THREAD

**Issue by allisonlu** [frctl/fractal-docs#84]
On the [Collection Configuration page](https://fractal.build/guide/collections/configuration-reference.html#collection-properties), the paragraph for property `order` appears above the h4 header: 

<img width="465" alt="screenshot of collection configuration properties" src="https://user-images.githubusercontent.com/8542413/105269001-ff5ca780-5b47-11eb-8fac-b5f8f63c947a.png">

**Comment by mihkeleidast** [comment]
Yeah. PR would be appreciated :)
